# Generated by Django 4.1.1 on 2023-01-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0020_alter_imghead_img_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imghead',
            name='img_pic',
            field=models.ImageField(blank=True, default='profile1.jpg', null=True, upload_to=''),
        ),
    ]
